### ISSUE TITLE
COPY oracle/version.go oracle/version.go file does not exists 

### ISSUE THREAD

**Issue by harishpadmanabhan93** [GoogleCloudPlatform/elcarro-oracle-operator#3] opened 2021-05-16 08:37 UTC
Step 8/19 : COPY oracle/version.go oracle/version.go
COPY failed: file not found in build context or excluded by .dockerignore: stat oracle/version.go: file does not exist

Getting the above error while installing the El carro oracle operator in Minikube

**Comment by yian-zhou** [comment] 2021-05-16 15:27
Thanks a lot for reporting the issue!

The cause of this issue is that the oracle/version.go file was excluded by .dockerignore but was used by operator dockerfile.

It was fixed via following commit: https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/commit/0cb9dd45673e9112e360f5ffed5241df779cf1d4

If you are using source code to build the operator image, feel free to add the oracle/version.go file following this commit.

Please let us know if you have any other questions. :-)
 
Cheers,
Yian

**Closed** 2021-05-16 16:00 UTC
